name: test
on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.22.0
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Run tests
      run: make test
    - name: Build
      run: make build-linux
